#!/bin/bash

# Are we up to date?
brew update

# Anything need to be upgraded?
brew upgrade

# Install core GNU utilities (OS X utilities are old)
brew install coreutils
echo "Don't forget to add $(brew --prefix coreutils)/libexec/gnubin to \$PATH."
" Install GNU `find`, `locate`, and `xargs`
brew install findutils

# Install wget
brew install wget --enable-iri

# Everything else
brew install ack
brew install git
brew install lynx
brew install node
brew install tree

# Remove outdated versions
brew cleanup
