# Dependences and settings
cask_args appdir: "/Applications"

tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts" # find fonts with: brew search font
tap "buo/cask-upgrade" # handle App Store app updates: brew cu
tap "homebrew/core"
tap "homebew/services"
brew "mas"

# macOS Utilities
brew "jordanbaird-ice"

# Languages
brew "go"
brew "golang-migrate"
brew "lua"
brew "node"
cask "r"
# no Python; use pyenv

# Language tools
brew "pyenv"

# CLI tools
brew "autojump"
brew "awscli"
brew "bat"
brew "caddy"
brew "ccache"
brew "cloc"
brew "coreutils"
brew "curl"
brew "duckdb"
brew "eza" # exa/ls replacement
brew "doctl"
brew "fd"
brew "fish" # fish shell
brew "fzf"
brew "gdal"
brew "gh" # GitHub CLI
brew "gibo" # sensible .gitignore defaults
brew "git"
brew "git-delta" # used in combination with lazygit
brew "git-lfs"
brew "gnu-sed"
brew "hugo"
brew "jq"
brew "lazygit"
brew "mactex"
brew "mosh"
brew "neovim"
brew "nmap"
brew "pandoc"
brew "postgresql", restart_services: true
brew "sqlite"
brew "task" # taskwarrior
brew "timewarrior"
brew "tmux"
brew "tree"
brew "wget"

# Dependencies 
brew "spatialite-tools"
brew "sqlite-utils"

# GUI apps
cask "basecamp"
cask "docker"
cask "fantastical"
cask "firefox"
cask "homebrew/cask-versions/firefox-developer-edition"
cask "iterm2"
cask "microsoft-auto-update"
cask "microsoft-excel"
cask "microsoft-word"
cask "obsidian"
cask "postico"
cask "qgis"
cask "rstudio"
cask "transmit"
cask "tropy"
cask "visual-studio-code"
cask "zoom"
cask "zotero"
mas "1Password", id: 1333542190
mas "Affinity Photo", id:824183456
mas "Affinity Designer", id:824171161
mas "Amphetamine", id:937984704
mas "Keynote", id:409183694
mas "PCalc", id:403504866
mas "PDF Expert", id:1055273043
mas "Slack", id:803453959
mas "Soulver 3", id:1508732804
mas "Things 3", id:904280696

# Fonts
cask "font-ibm-plex"
cask "font-fira-code"
cask "font-inconsolata"
cask "font-source-sans-3"
