# Dependences and settings

cask_args appdir: "/Applications"

tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/core"
tap "homebew/services"

brew "mas"

# Languages
brew "go"
brew "node"
brew "r"
brew "ruby"

# Language tools
brew "pyenv"
brew "rbenv"

# CLI tools
brew "autojump"
brew "awscli"
brew "bat"
brew "caddy"
brew "ccache"
brew "cloc"
brew "coreutils"
brew "curl"
brew "duckdb"
brew "eza"
brew "doctl"
brew "fd"
brew "fzf"
brew "gdal"
brew "gh"
brew "gibo"
brew "git"
brew "git-lfs"
brew "gnu-sed"
brew "golang-migrate"
brew "hugo"
brew "jq"
brew "mactex"
brew "mosh"
brew "neovim"
brew "nmap"
brew "pandoc"
brew "postgresql", restart_services: true
brew "sqlite"
brew "tree"
brew "wget"
brew "zsh-syntax-highlighting"

# Dependencies 
brew "spatialite-tools"
brew "sqlite-utils"

# GUI apps
cask "basecamp"
cask "docker"
cask "fantastical"
cask "homebrew/cask-versions/firefox-developer-edition"
cask "ghostty"
cask "microsoft-auto-update"
cask "microsoft-excel"
cask "microsoft-word"
cask "obsidian"
cask "postico"
cask "qgis"
cask "rstudio"
cask "transmit"
cask "tropy"
cask "visual-studio-code"
cask "zoom"
cask "zotero"
mas "1Password", id: 1333542190
mas "Affinity Photo", id:824183456
mas "Affinity Designer", id:824171161
mas "Amphetamine", id:937984704
mas "Keynote", id:409183694
mas "PCalc", id:403504866
mas "PDF Expert", id:1055273043
mas "Slack", id:803453959
mas "Soulver 3", id:1508732804
mas "Things 3", id:904280696

# Fonts
cask "font-ibm-plex"
cask "font-fira-code"
cask "font-inconsolata"
