# Test for interactive shell
if [[ $- != *i* ]]; then
  # Shell is non-interactive. Be done!
  return
fi

# Load bashrc
if [ -f ~/.bashrc ]; then
    source ~/.bashrc
fi

# Load bash_completion if exists
if [ -f /etc/bash_completion ]; then
    . /etc/bash_completion
fi

# Load git_completion if exists
if [ -f ~/.git_completion.sh ]; then
  source ~/.git_completion.sh
fi

export PATH=/usr/local/bin:/usr/local/sbin:$PATH
#export PATH="$HOME/Library/Haskell/bin:$PATH"
#export PATH="$HOME/.cabal/bin:$PATH"
export LC_CTYPE=en_US.UTF-8 
export PS1="\[\e[0;32m\]\W @ \h (\u) \n\$ \[\e[m\]" 
export EDITOR="subl -w"
#ignore certain commands from history: duplicates, ls, bg, fg, and exit
export HISTIGNORE="&:ls:[bf]g:exit"
export NODE_PATH="/usr/local/lib/node_modules"
export PYTHONPATH="/usr/local/lib/python:/usr/local/share/python:/usr/local/lib/python2.7/site-packages"
set -o vi
alias ls="ls -F"

# Colors
#export CLICOLOR=1
#export LSCOLORS=Gxfxcxdxbxegedabagacad

# export PATH="$HOME/.rbenv/bin:$PATH"
# eval "$(rbenv init -)"
# Setting PATH for Python 3.4
# The orginal version is saved in .bash_profile.pysave
PATH="/Library/Frameworks/Python.framework/Versions/3.4/bin:${PATH}"
export PATH

# Add GHC 7.10.1 to the PATH, via https://ghcformacosx.github.io/
export GHC_DOT_APP="/Users/jheppler/Downloads/ghc-7.10.1.app"
if [ -d "$GHC_DOT_APP" ]; then
  export PATH="${HOME}/.cabal/bin:${GHC_DOT_APP}/Contents/bin:${PATH}"
fi

