#if [ -f ~/.bash_profile ]; then
#	source ~/.bash_profile
#fi

unset MAILCHECK

# added by travis gem
[ -f /Users/jheppler/.travis/travis.sh ] && source /Users/jheppler/.travis/travis.sh

# Add GHC 7.10.1 to the PATH, via https://ghcformacosx.github.io/
export GHC_DOT_APP="/Applications/ghc-7.10.1.app"
if [ -d "$GHC_DOT_APP" ]; then
  export PATH="${HOME}/.cabal/bin:${GHC_DOT_APP}/Contents/bin:${PATH}"
fi
